# Generated by Django 4.2.1 on 2023-05-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='url')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='Город проживания')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('grade', models.IntegerField(blank=True, default=0, verbose_name='Класс')),
                ('tests', models.ManyToManyField(blank=True, to='edu.test', verbose_name='Тесты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль ользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
