# Generated by Django 4.2.1 on 2023-06-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('edu', '0003_alter_answer_options_testanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testanswers', to='edu.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testanswers', to='users.profile', verbose_name='Пользователь'),
        ),
    ]
