# Generated by Django 4.2.1 on 2023-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_testanswer_test_alter_testanswer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='tasks_list',
            field=models.ManyToManyField(related_name='test', to='edu.task'),
        ),
    ]
